name: quit_smoking_app
description: 禁煙記録アプリ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  image_path: "assets/icons/app_icon_512.png"
  android: true
  adaptive_icon_foreground: "assets/icons/adaptive_icon_foreground.png"
  adaptive_icon_background: "#2E7D32"
  ios: true
  web:
    generate: true
    background_color: "#2E7D32"
    theme_color: "#2E7D32"
  windows:
    generate: true
  macos:
    generate: true
